[GLOBAL]
pants_version = "2.17.0"
pythonpath = ["%(buildroot)s/src/pants-plugins"]

backend_packages = [
  "pants.backend.shell",
  "pants.backend.python",
  "pants.backend.experimental.python",
  "pants.backend.python.mixed_interpreter_constraints",
  "pants.backend.build_files.fmt.buildifier",
]

[python-bootstrap]
search_path = ["<ASDF_LOCAL>", "<ASDF>", "<PATH>"]

[python]
interpreter_constraints = [">=3.11.*"]
enable_resolves = true
default_resolve = "python-default"

[python-infer]
use_rust_parser = true

[python.resolves]
python-default = "3rdparty/python/default.lock"

[source]
root_patterns = [
  '/src',
]
